name: Valetudo Proxy
version: "1.1"
panel_icon: "valetudo:valetudo"
panel_title: Valetudo
slug: valetudo-proxy
description: Valetudo proxy addon
url: "https://github.com/K0n24d/custom-hass-addons/valetudo_proxy"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:80]/"
watchdog: "http://[HOST]:[PORT:80]/"
ingress: true
ingress_port: 80
ingress_entry: /
panel_admin: false
ports:
  80/tcp: 80
ports_description:
  80/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "http://valetudo.local:80/"
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  server: "match(^https?://.+:\\d+/$)"
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
